# Generated by Django 3.1.7 on 2021-03-05 11:52

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210104_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=api.models.generateUniqueCode, max_length=8, unique=True),
        ),
    ]
